stages:
  - clone
  - test

clone_repository:
  stage: clone
  script:
    - git clone https://github.com/NicolasAndrade1605/Teste_API---Jos--Carlos.git .
    - npm install

run_tests:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - reports/

