stages:
  - install
  - test

install_dependencies:
  image: node:22
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

run_tests:
  image: node:22
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - reports/
    when: always
